function current_error = compute_current_error(residue_matrix_b_minus_currentPBN, ...
                                               list_of_BN_matrices_in_terms_of_pos, ...
                                               current_PBN_matrix_found, ...
                                               matrix_of_nonzero_positions, ... 
                                               num_of_nonzero_entries_each_col, ...
                                               stopping_criteria_type, ...
                                               input_matrix_row_num, input_matrix_col_num)
    if stopping_criteria_type == "according_to_page_9_of_the_paper"
        current_error = compute_current_error_according_to_page_9(residue_matrix_b_minus_currentPBN, ...
                                                                  list_of_BN_matrices_in_terms_of_pos, ...
                                                                  current_PBN_matrix_found, ...
                                                                  matrix_of_nonzero_positions, ... 
                                                                  num_of_nonzero_entries_each_col, ...
                                                                  input_matrix_row_num, ...
                                                                  input_matrix_col_num);
    elseif stopping_criteria_type == "the_obvious_difference_Ax_minus_b"
        residue_matrix_b_minus_currentPBN_flattened = flatten_matrix_to_col_vec(residue_matrix_b_minus_currentPBN, ...
                                                                                input_matrix_row_num, ...
                                                                                input_matrix_col_num);
        current_error = realsqrt(residue_matrix_b_minus_currentPBN_flattened' * ...
                                 residue_matrix_b_minus_currentPBN_flattened);
    end
end