% list_of_BN_coefficients 疑似係一個 redundant parameter/argument.
function current_error = compute_current_error_according_to_page_9(residue_matrix_b_minus_currentPBN, ...
                                                                   list_of_BN_matrices_in_terms_of_pos, ...
                                                                   current_PBN_matrix_found, ...
                                                                   matrix_of_nonzero_positions, ... 
                                                                   num_of_nonzero_entries_each_col, ...
                                                                   input_matrix_row_num, ...
                                                                   input_matrix_col_num)
    % Compute (A * x^k)^{T} * r^k.
    residue_matrix_flattened_rk = flatten_matrix_to_col_vec(residue_matrix_b_minus_currentPBN, ...
                                                            input_matrix_row_num, input_matrix_col_num);
    current_PBN_found_flattened_A_xk = flatten_matrix_to_col_vec(current_PBN_matrix_found, ...
                                                                 input_matrix_row_num, input_matrix_col_num);
    a_constant_to_subtract = current_PBN_found_flattened_A_xk' * residue_matrix_flattened_rk;

    % Compute the two Euclidean norms.
    total_number_of_constituent_BNs = prod(num_of_nonzero_entries_each_col, "all");
    sum_in_the_support = 0;  % Haven't taken the square root yet.
    sum_outside_the_support = 0;  % Haven't taken the square root yet.
    current_BN_itf_positions_untransformed = ones(input_matrix_col_num, 1);

    for count = 1 : total_number_of_constituent_BNs
        current_BN_itf_positions_transformed = transform_BN_positions(current_BN_itf_positions_untransformed, ...
                                                                      input_matrix_col_num, ...
                                                                      matrix_of_nonzero_positions);
        dot_prod_between_current_BN_and_rk = 0;
        for col_count = 1 : input_matrix_col_num
            dot_prod_between_current_BN_and_rk = dot_prod_between_current_BN_and_rk + ...
                residue_matrix_b_minus_currentPBN(current_BN_itf_positions_transformed(col_count), col_count);
        end

        if ismember(current_BN_itf_positions_transformed', list_of_BN_matrices_in_terms_of_pos', 'rows')
            sum_in_the_support = sum_in_the_support + ...
                (dot_prod_between_current_BN_and_rk - a_constant_to_subtract)^2;
        else  % if the current BN matrix is not in the support (i.e., not a column of list_of_BN_matrices_in_terms_of_pos)
            sum_outside_the_support = sum_outside_the_support + ...
                (max(dot_prod_between_current_BN_and_rk - a_constant_to_subtract, 0))^2;
        end

        % Update current_BN_itf_positions_untransformed.
        current_BN_itf_positions_untransformed = ...
            special_num_system_incrementation(current_BN_itf_positions_untransformed, input_matrix_col_num, ...
                                              num_of_nonzero_entries_each_col, 1);
    end

    current_error = sqrt(sum_in_the_support) + sqrt(sum_outside_the_support);
end